Repository zuri-training/favicon-gen-team-66, pull requests merged in 2022-08, with the labels that each got.

#43 Register user endpoint
  .gitignore
  README.md
  apps/account/serializer.py
  apps/account/urls.py
  apps/account/views.py
  requirements.txt
  team66/settings.py
  team66/urls.py
Labels: backend, completed

#44 Endpoint updates
  .gitignore
  README.md
  apps/account/permissions.py
  apps/account/serializer.py
  apps/account/urls.py
  apps/account/views.py
  requirements.txt
  team66/settings.py
  team66/urls.py
Labels: backend, completed

#88 lucky_contributions.md
  Lucky_contibution.md
Labels: design, completed

#90 Create luckii_contribution.md
  Contribution/luckii_contribution.md
Labels: design, completed

#118 Updated the favicon page html and css code and added javasript code
  Contribution/NicholasContributio.md
  frontend/static/account/favicon(modal).css
  frontend/static/account/favicon.css
  frontend/templates/account/favicon(modal).html
  frontend/templates/account/favicon.html
  frontend/templates/account/favicon.js
Labels: frontend

#125 updated user profile
  Contribution/I4G006916U67-contribution.md
  I4G007774RQU-contributions.md
  apps/account/migrations/0001_initial.py
  apps/account/migrations/0002_userprofile_name.py
  apps/account/migrations/0003_userprofile_is_staff.py
  apps/account/migrations/0004_rename_first_name_userprofile_username.py
  apps/account/models.py
  apps/account/permissions.py
  apps/account/serializer.py
  apps/account/views.py
  apps/faviconer/views.py
  frontend/templates/account/images/images_5_1646449595151.jpeg
  frontend/templates/account/images/images_5_1646449595151_fiB0k4v.jpeg
  frontend/templates/account/images/unnamed.jpg
  requirements.txt
  team66/settings.py
  team66/urls.py
Labels: backend
